server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 54321
        driver-class-name: org.postgresql.Driver
        initialize: true

    jpa: 
        hibernate:
            # naming:
            #     physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: none
            generate-ddl: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
